enable:
  issues: true
  prs: true

# 레이블을 성공적으로 붙이고 PR에 보낼 코멘트를 설정
comments:
  issues: |
    this is issue.
  prs: |
    Labeler has applied any labels matching special text in your title and description.
    Please review the labels and make any necessary changes.

# 레이블
labels:
  ':bug: BUG':
    include: ['fix', '\bFix\b', '\bfix\b']

  ':sparkles: FEAT':
    include: ['\bFeat\b', '\bFEAT\b', '\bfeat\b']

  ':page_with_curl: DOCS':
    include:
      ['\bDocs\b', '\bDOCS\b']

  ':tada: INIT':
    include:
      ['\bInit\b', '\bINIT\b']
  
  ':lipstick: DESIGN':
    include:
      ['\bDesign\b', '\bDESIGN\b']

  'CHORE':
    include:
      ['\bCHORE\b', '\bChore\b']
  ':page_with_curl: DOCS':
    include:
      ['\bDocs\b', '\bDOCS\b']
