enable:
  issues: true
  prs: true

labels:
  ':bug: BUG':
    include: ['\bFix\b', '\bfix\b', '\bFIX\b']

  ':sparkles: FEAT':
    include: ['\bFeat\b', '\bFEAT\b', '\bfeat\b']

  ':page_with_curl: DOCS':
    include:
      ['\bDocs\b', '\bDOCS\b',  '\bdocs\b']

  ':tada: INIT':
    include:
      ['\bInit\b', '\bINIT\b', '\init\b']
  
  ':lipstick: DESIGN':
    include:
      ['\bDesign\b', '\bDESIGN\b', '\bdesign\b']

  ':broom: CHORE':
    include:
      ['\bCHORE\b', '\bChore\b', '\bchore\b']

  ':hammer: REFACTOR':
    include:
      ['\bRefactor\b', '\bREFACTOR\b', '\brefactor\b']

