name: Labeler
on:
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened]
    

jobs:
  label:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
    - id: label
      uses: actions/labeler@v4
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
